image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7

before_script:
  - yum install -y libgfortran make atlas
  - source /cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc9-opt/setup.sh
  - python -m venv venv
  - source venv/bin/activate

test_setup:
  tags:
    - cvmfs
  script:
    - python setup.py build
    - python setup.py test
test_pip:
  tags:
    - cvmfs
  script:
    - pip install .
    - cd tests
    - pytest
